apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-istio
spec:
  hosts:
  - "hello-istio.cloud"
  gateways:
  - hello-istio-gateway
  http:
  # try adding HTTP delay of 3s to requests with User-Agent ChaosMonkey
  # try adding HTTP abort fault to requests with User-Agent ChaosMonkey
  - route:
    - destination:
        host: hello-istio
        subset: v1
      weight: 100